scope: ecommerce-cluster
namespace: /service/
name: __PATRONI_NAME__

restapi:
  listen: 0.0.0.0:8008
  connect_address: __PATRONI_NAME__:8008

etcd3:
  hosts: etcd1:2379,etcd2:2379,etcd3:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10

    postgresql:
      use_pg_rewind: true
      use_slots: true

      parameters:
        wal_level: replica
        hot_standby: "on"
        wal_keep_size: 128MB
        max_wal_senders: 10
        max_replication_slots: 10

  initdb:
    - encoding: UTF8
    - data-checksums

  pg_hba:
    - host replication replicator 0.0.0.0/0 scram-sha-256
    - host all all 0.0.0.0/0 scram-sha-256

  users:
    admin:
      password: admin
      options:
        - createrole
        - createdb

    replicator:
      password: replicator_password
      options:
        - replication

postgresql:
  listen: 0.0.0.0:5432
  connect_address: __PATRONI_NAME__:5432

  data_dir: /var/lib/postgresql/data

  authentication:
    superuser:
      username: postgres
      password: postgres

    replication:
      username: replicator
      password: replicator_password

  parameters:
    max_connections: 200

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false